@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package panda.divergentunderground.init;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;